### ISSUE TITLE
新Call10 已开源

### ISSUE THREAD

**Issue by HyperSimon** [wangkun11/CallTen#1]
好吧，我知道不应该放到这里面 。
新版Call10已经开源，这是地址 https://github.com/SimonWang1996/Call10  
不定时更新 XD

**Comment by wangkun11** [comment]
刚访问了一下，404错误，是不是移动了

**Comment by HyperSimon** [comment]
嗯 确实移动了，新地址在这 https://github.com/roselism/CallPP
